name: CMake build and test
description: CMake build and test workflow

runs:
  using: "composite"

  steps:
  - name: CMake configure
    shell: bash
    run: |
      cmake --preset default \
            -DSC_ENABLE_MPI:BOOL=${{ matrix.mpi }} \
            -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }} \
            $SC_CI_CONFIG_OPT

  - name: CMake print debug find
    shell: bash
    if: failure()
    run: |
      cmake --preset default \
            -DSC_ENABLE_MPI:BOOL=${{ matrix.mpi }} \
            -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }} \
            $SC_CI_CONFIG_OPT \
            --debug-find --fresh

  - name: CMake build and test
    shell: bash
    run: cmake --workflow default

  - name: CMake install (for examples)
    shell: bash
    run: cmake --install build

  - name: CMake build and test examples
    shell: bash
    run: cmake --workflow default
    working-directory: example

  - name: Create package
    shell: bash
    if: github.event.action == 'published'
    run: cpack --config build/CPackConfig.cmake

  - name: Upload package
    if: github.event.action == 'published'
    uses: actions/upload-artifact@v7
    with:
      name: ${{ github.job }}-binary-archive-${{ matrix.cc }}-mpi-${{ matrix.mpi }}-shared-${{ matrix.shared }}
      path: build/package

  - name: Upload log files
    if: always()
    uses: actions/upload-artifact@v7
    with:
      name: ${{ github.job }}_cmake_log-${{ matrix.cc }}-mpi-${{ matrix.mpi }}-shared-${{ matrix.shared }}
      path: |
        ./build/CMakeFiles/CMakeConfigureLog.yaml
        ./build/Testing/Temporary/LastTest.log
