name: CI for CMake

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - "**.cmake.in"
      - "**.c"
      - "**.h"
      - "**.h.in"
      - ".github/workflows/ci_cmake.yml"
  pull_request:
  release:
    types: [published]

env:
  # Due to busy file system problems on the CI runners, we deactivate the file
  # checks in the CI.
  SC_CI_CONFIG_OPT: -DSC_ENABLE_FILE_CHECKS=OFF

jobs:

  ubuntu-24:
    runs-on: ubuntu-24.04
    name: Linux mpi=${{ matrix.mpi }} CC=${{ matrix.cc }} shared=${{ matrix.shared }}
    timeout-minutes: 60

    strategy:
      matrix:
        cc: [gcc, clang]
        shared: [false]
        mpi: [true, false]
# we only include one "shared=true" as it's less common usage
# but we want to be sure CMake is OK with it
        include:
        - cc: gcc
          shared: true
          mpi: true

    env:
      CC: ${{ matrix.cc }}

    steps:
    - &checkout
      uses: actions/checkout@v6
      name: Checkout source code

    - name: Install system dependencies
      if: ${{ matrix.mpi }}
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends \
            libmpich-dev mpich

    - name: CMake composite steps (build, test, install, examples)
      uses: ./.github/workflows/composite-cmake


  linux-valgrind:
    needs: ubuntu-24
    runs-on: ubuntu-24.04
    name: Valgrind Linux mpi=${{ matrix.mpi }} CC=${{ matrix.cc }}
    timeout-minutes: 60

    strategy:
      matrix:
        cc: [gcc]
        mpi: [true]
        valgrind: [ON]

    env:
      CC: ${{ matrix.cc }}

    steps:
    - name: Install system dependencies
      run: |
        sudo apt-get update -yq
        sudo apt-get install -yq --no-install-recommends \
            libmpich-dev mpich valgrind

    - *checkout

    - name: CMake configure
      run: |
        cmake --preset default -DSC_ENABLE_MPI:BOOL=${{ matrix.mpi }} \
              -DSC_TEST_WITH_VALGRIND:BOOL=${{ matrix.valgrind }} \
              $SC_CI_CONFIG_OPT

    - name: CMake build
      run: cmake --build --preset default

    - name: CMake Test
      run: ctest --preset default

    - name: Upload log files
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: linux_cmake_valgrind_log
        path: |
          ./build/CMakeFiles/CMakeConfigureLog.yaml
          ./build/Testing/Temporary/LastTest.log

  mac:
    runs-on: macos-latest
    name: macOS mpi=${{ matrix.mpi }} CC=${{ matrix.cc }} shared=${{ matrix.shared }}
    timeout-minutes: 60

    strategy:
      matrix:
        cc: [clang]
        mpi: [true]
        shared: [false, true]

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      CC: ${{ matrix.cc }}

    steps:
    - *checkout

    - name: Install system dependencies
      run: brew install open-mpi

    - name: CMake composite steps (build, test, install, examples)
      uses: ./.github/workflows/composite-cmake

  windows:
    runs-on: windows-latest
    name: Windows
    timeout-minutes: 60

    strategy:
      matrix:
        shared: [false]
        mpi: [false]
    # GitHub Action Windows shared libs is generally broken, even with MSYS2, but works on real laptops etc.

    env:
      CMAKE_GENERATOR: Ninja

    steps:
    - *checkout

    - name: CMake composite steps (build, test, install, examples)
      uses: ./.github/workflows/composite-cmake
